import { z } from 'zod';

/**
 * Design Token System
 * Defines structured theme configuration that can be generated by AI
 * and converted to CSS variables at runtime
 */

// Color tokens
export const ColorTokenSchema = z.object({
  r: z.number().min(0).max(255),
  g: z.number().min(0).max(255),
  b: z.number().min(0).max(255),
  alpha: z.number().min(0).max(1).optional().default(1),
});

export type ColorToken = z.infer<typeof ColorTokenSchema>;

// Typography tokens
export const TypographyTokenSchema = z.object({
  fontFamily: z.string(),
  fontSize: z.string(), // e.g., "1rem", "16px"
  fontWeight: z.union([
    z.literal('100'),
    z.literal('200'),
    z.literal('300'),
    z.literal('400'),
    z.literal('500'),
    z.literal('600'),
    z.literal('700'),
    z.literal('800'),
    z.literal('900'),
  ]).optional(),
  lineHeight: z.string().optional(),
  letterSpacing: z.string().optional(),
});

export type TypographyToken = z.infer<typeof TypographyTokenSchema>;

// Spacing tokens
export const SpacingTokenSchema = z.object({
  xs: z.string(),
  sm: z.string(),
  md: z.string(),
  lg: z.string(),
  xl: z.string(),
  '2xl': z.string().optional(),
  '3xl': z.string().optional(),
});

export type SpacingToken = z.infer<typeof SpacingTokenSchema>;

// Border radius tokens
export const BorderRadiusTokenSchema = z.object({
  sm: z.string(),
  md: z.string(),
  lg: z.string(),
  full: z.string().optional(),
});

export type BorderRadiusToken = z.infer<typeof BorderRadiusTokenSchema>;

// Shadow tokens
export const ShadowTokenSchema = z.object({
  sm: z.string(),
  md: z.string(),
  lg: z.string(),
  xl: z.string().optional(),
});

export type ShadowToken = z.infer<typeof ShadowTokenSchema>;

// Complete theme configuration
export const ThemeConfigSchema = z.object({
  colors: z.object({
    primary: ColorTokenSchema,
    secondary: ColorTokenSchema.optional(),
    accent: ColorTokenSchema.optional(),
    success: ColorTokenSchema.optional(),
    warning: ColorTokenSchema.optional(),
    error: ColorTokenSchema.optional(),
    background: z.object({
      primary: ColorTokenSchema,
      secondary: ColorTokenSchema.optional(),
      tertiary: ColorTokenSchema.optional(),
    }),
    text: z.object({
      primary: ColorTokenSchema,
      secondary: ColorTokenSchema.optional(),
      tertiary: ColorTokenSchema.optional(),
    }),
    border: ColorTokenSchema.optional(),
  }),
  typography: z.object({
    fontFamily: z.object({
      sans: z.string(),
      mono: z.string().optional(),
      serif: z.string().optional(),
    }),
    heading: TypographyTokenSchema.optional(),
    body: TypographyTokenSchema.optional(),
  }),
  spacing: SpacingTokenSchema,
  borderRadius: BorderRadiusTokenSchema,
  shadows: ShadowTokenSchema.optional(),
  transitions: z.object({
    fast: z.string().optional(),
    base: z.string().optional(),
    slow: z.string().optional(),
  }).optional(),
});

export type ThemeConfig = z.infer<typeof ThemeConfigSchema>;

/**
 * Default theme configuration
 */
export const defaultTheme: ThemeConfig = {
  colors: {
    primary: { r: 59, g: 130, b: 246 },
    secondary: { r: 107, g: 114, b: 128 },
    accent: { r: 147, g: 197, b: 253 },
    success: { r: 34, g: 197, b: 94 },
    warning: { r: 234, g: 179, b: 8 },
    error: { r: 239, g: 68, b: 68 },
    background: {
      primary: { r: 255, g: 255, b: 255 },
      secondary: { r: 249, g: 250, b: 251 },
      tertiary: { r: 243, g: 244, b: 246 },
    },
    text: {
      primary: { r: 17, g: 24, b: 39 },
      secondary: { r: 107, g: 114, b: 128 },
      tertiary: { r: 156, g: 163, b: 175 },
    },
    border: { r: 229, g: 231, b: 235 },
  },
  typography: {
    fontFamily: {
      sans: 'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
      mono: 'ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, "Liberation Mono", monospace',
    },
    heading: {
      fontFamily: 'ui-sans-serif, system-ui',
      fontSize: '1.5rem',
      fontWeight: '600',
    },
    body: {
      fontFamily: 'ui-sans-serif, system-ui',
      fontSize: '1rem',
      fontWeight: '400',
    },
  },
  spacing: {
    xs: '0.25rem',
    sm: '0.5rem',
    md: '1rem',
    lg: '1.5rem',
    xl: '2rem',
    '2xl': '3rem',
    '3xl': '4rem',
  },
  borderRadius: {
    sm: '0.25rem',
    md: '0.5rem',
    lg: '0.75rem',
    full: '9999px',
  },
  shadows: {
    sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
    md: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
    lg: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
  },
  transitions: {
    fast: '150ms ease-in-out',
    base: '200ms ease-in-out',
    slow: '300ms ease-in-out',
  },
};

